In [1]:
import numpy as np

In [3]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [4]:
def liner(x):
    return x

In [5]:
x=np.array([1,2])
print(x.shape)

(2,)


In [6]:
w=np.array([[1,2,3],[4,5,6]])
print(w.shape)

(2, 3)


In [8]:
np.dot(x,w)

array([ 9, 12, 15])

In [9]:
x = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5],[0.2, 0.4, 0.6]])
b1 = np.array([0.1, 0.2, 0.3])
a1 = np.dot(x, W1) + b1 
print(a1)

[0.3 0.7 1.1]


In [10]:
z1 = sigmoid(a1)
print(z1)

[0.57444252 0.66818777 0.75026011]


In [11]:
W2 = np.array([[0.1, 0.4],[0.2, 0.5], [0.3, 0.6]])
b2 = np.array([0.1, 0.2])
a2 = np.dot(z1, W2) + b2
print(a2)

[0.51615984 1.21402696]


In [12]:
z2 = sigmoid(a2)
print(z2)

[0.62624937 0.7710107 ]
