# 各種レイヤがバッチ処理に対応していることを確認する

In [1]:
import numpy as np

## 加算レイヤ

In [2]:
class AddLayer:
    def __init__(self):
        pass # 何もしない
        
    def forward(self, x, y):
        return x + y
    
    def backward(self, dout):
        """
        dout : float, 上流(出力)側の勾配
        """
        dLdx = dout
        dLdy = dout
        return dLdx, dLdy

In [3]:
al = AddLayer()
x = np.array([[1],[2]])
y = np.array([[3],[4]])
dout = np.array([5])

print("forward=\n", al.forward(x, y))

dLdx , dLdy = al.backward(dout)
print("dLdx=\n", dLdx)
print("dLdy=\n", dLdy)

forward=
 [[4]
 [6]]
dLdx=
 [5]
dLdy=
 [5]


## 乗算レイヤ

In [4]:
class MultiLayer:
    def __init__(self):
        self.x = None
        self.y = None
        
    def forward(self, x, y):
        self.x = x #記憶しておく
        self.y = y #記憶しておく
        return x * y
    
    def backward(self, dout):
        """
        dout : float, 上流(出力)側の勾配
        """        
        dLdx = dout * self.y
        dLdy = dout * self.x
        return dLdx, dLdy

In [5]:
ml = MultiLayer()
x = np.array([[1],[2]])
y = np.array([[3],[4]])
dout = np.array([5])

print("forward=\n", ml.forward(x, y))

dLdx , dLdy = ml.backward(dout)
print("dLdx=\n", dLdx)
print("dLdy=\n", dLdy)

forward=
 [[3]
 [8]]
dLdx=
 [[15]
 [20]]
dLdy=
 [[ 5]
 [10]]


## ReLUレイヤ

In [6]:
class ReLU:
    def __init__(self):
        self.mask = None
        
    def forward(self, x):
        self.mask = (x <= 0)
        out = x.copy() #参照渡しではなく複製する
        out[self.mask] = 0
        return out
    
    def backward(self, dout):
        """
        dout : float, 上流(出力)側の勾配
        """        
        dout[self.mask] = 0
        dLdx = dout
        return dLdx

In [7]:
rl = ReLU()
x = np.array([[1],[-1],[0]])
dout = np.array([[3],[3],[3]])

print("forward=\n", rl.forward(x))

dLdx = rl.backward(dout)
print("dx=\n", dLdx)

forward=
 [[1]
 [0]
 [0]]
dx=
 [[3]
 [0]
 [0]]


## Sigmoidレイヤ

In [8]:
class Sigmoid:
    def __init__(self):
        self.out = None
        
    def forward(self, x):
        out = 1 / (1 + np.exp(-x))
        self.out = out # 記憶しておく
        return out
    
    def backward(self, dout):
        """
        dout : float, 上流(出力)側の勾配
        """        
        dLdx = dout * self.out * (1.0 - self.out)
        return dLdx

In [9]:
sm = Sigmoid()
x = np.array([[-10],[0],[10]])
dout = np.array([[3],[3],[3]])

print("forward=\n", sm.forward(x))

dLdx = sm.backward(dout)
print("dLdx=\n", dLdx)

forward=
 [[4.53978687e-05]
 [5.00000000e-01]
 [9.99954602e-01]]
dLdx=
 [[1.36187423e-04]
 [7.50000000e-01]
 [1.36187423e-04]]
