# Softmax_with_Lossレイヤの実装

In [1]:
import numpy as np
from common.activations import softmax
from common.loss import cross_entropy_error

## Softmax_with_Lossの実装

### [演習]
* 以下のSoftmax_with_Lossクラスを完成させましょう

In [2]:
class SoftmaxWithLoss:
    def __init__(self):
        
        # 初期値
        self.loss = None
        self.y = None # softmaxの出力
        self.t = None # 正解データ

    def forward(self, x, t):
        """
        順伝播
        """
        self.t = t
        self.y = softmax(x)
        self.loss = cross_entropy_error(self.y, self.t)
        
        return self.loss

    def backward(self, dout=1):
        """
        逆伝播
        伝播する値をバッチサイズで割ること
        dout=1は、他のレイヤと同じ使い方ができるように設定しているダミー変数
        """
        batch_size = self.t.shape[0]
        dx = (self.y - self.t) / batch_size

        return dx

In [3]:
# 行列入力
x = np.array([
            [1, 2, 3],
            [3, 2, 1]])
t = np.array([
            [0, 0, 1],
            [1, 0, 0]])

# 順伝播
softmaxloss = SoftmaxWithLoss()
out = softmaxloss.forward(x, t)
print("forward=", out)
print()
print("ソフトマックスの出力結果=\n", softmaxloss.y)
print()

# 逆伝播
dLdx = softmaxloss.backward()
print("dLdx=\n", dLdx)

forward= 0.4076058141229194

ソフトマックスの出力結果=
 [[0.09003057 0.24472847 0.66524096]
 [0.66524096 0.24472847 0.09003057]]

dLdx=
 [[ 0.04501529  0.12236424 -0.16737952]
 [-0.16737952  0.12236424  0.04501529]]
