# ドロップアウト(dropout)

In [1]:
import numpy as np

### [演習]
* 以下のドロップアウトレイヤを完成させましょう

In [2]:
# ヒント
x = np.array([[1,2,3], [4,5,6]])
print("x=", x)
print()
print("x.shape=", x.shape)
print()
print("変数の前に*をつけると、tupleの要素を取り出せる")
print(*x.shape )
print()
print(np.random.rand(*x.shape))
print()
dropout_ratio = 0.3
mask = np.random.rand(*x.shape) > dropout_ratio
print(mask)
print()
print(x*mask)

x= [[1 2 3]
 [4 5 6]]

x.shape= (2, 3)

変数の前に*をつけると、tupleの要素を取り出せる
2 3

[[0.24932525 0.38434952 0.36374901]
 [0.38168676 0.43134916 0.97854127]]

[[False  True  True]
 [False  True  True]]

[[0 2 3]
 [0 5 6]]


In [3]:
class Dropout:
    def __init__(self, dropout_ratio=0.5):
        """
        dropout_ratio : ドロップアウトする割合
        """
        self.dropout_ratio = dropout_ratio
        self.mask = None

    def forward(self, x, train_flg=True):
        """
        順伝播計算の関数
        """
        if train_flg:
            """
            学習時
            """
            self.mask = np.random.rand(*x.shape) > self.dropout_ratio
            return x * self.mask
        else:
            """
            予測時は、ドロップアウトしなかった（残した)割合をかける
            すべてのノードを採用すると、学習時に比べ結合後の値が大きくなるので、
            残した割合を掛けることにより、値を調整している。
            """
            return x * (1.0 - self.dropout_ratio)

    def backward(self, dout):
        """
        逆伝播計算の関数
        順伝播計算時に使用したノードだけ、誤差を伝播させる
        """
        return dout * self.mask

In [4]:
x = np.array([[1,2,3], [4,5,6],[7,8,9]])
print("x=")
print(x)
print()

do = Dropout(dropout_ratio=0.8)
print("順伝播時、ドロップアウト層通過後=")
print(do.forward(x))
print()
print("逆伝播時、ドロップアウト層通過後=")
print(do.backward(dout=1.234))

x=
[[1 2 3]
 [4 5 6]
 [7 8 9]]

順伝播時、ドロップアウト層通過後=
[[0 0 3]
 [0 0 6]
 [7 0 0]]

逆伝播時、ドロップアウト層通過後=
[[0.    0.    1.234]
 [0.    0.    1.234]
 [1.234 0.    0.   ]]
