# padding、reshape、transposeの動作確認

In [1]:
import numpy as np

## paddingの動作確認

In [2]:
print("1次元")
input_data = np.random.randn(2).round(2)
print("input_data=")
print(input_data)
pad = 1
pad_data = np.pad(input_data, [ (pad, pad)], 'constant')
print("pad_data=")
print(pad_data)
print()

print("2次元")
input_data = np.random.randn(2,2).round(2)
print("input_data=")
print(input_data)
pad = 1
pad_data = np.pad(input_data, [ (pad, pad), (0, 0)], 'constant')
print("pad_data=")
print(pad_data)
print()

print("2次元")
input_data = np.random.randn(2,2).round(2)
print("input_data=")
print(input_data)
pad = 1
pad_data = np.pad(input_data, [ (pad, pad), (pad, pad)], 'constant')
print("pad_data=")
print(pad_data)
print()

print("3次元")
input_data = np.random.randn(2,2,2).round(2)
print("input_data=")
print(input_data)
pad = 1
pad_data = np.pad(input_data, [ (pad, pad), (pad, pad), (pad, pad)], 'constant')
print("pad_data=")
print(pad_data)
print()

1次元
input_data=
[ 0.11 -2.07]
pad_data=
[ 0.    0.11 -2.07  0.  ]

2次元
input_data=
[[1.23 1.3 ]
 [0.83 0.89]]
pad_data=
[[0.   0.  ]
 [1.23 1.3 ]
 [0.83 0.89]
 [0.   0.  ]]

2次元
input_data=
[[ 1.55  0.03]
 [-0.11 -0.61]]
pad_data=
[[ 0.    0.    0.    0.  ]
 [ 0.    1.55  0.03  0.  ]
 [ 0.   -0.11 -0.61  0.  ]
 [ 0.    0.    0.    0.  ]]

3次元
input_data=
[[[ 0.21 -1.02]
  [-0.66  1.7 ]]

 [[-0.76 -1.25]
  [ 0.27  0.58]]]
pad_data=
[[[ 0.    0.    0.    0.  ]
  [ 0.    0.    0.    0.  ]
  [ 0.    0.    0.    0.  ]
  [ 0.    0.    0.    0.  ]]

 [[ 0.    0.    0.    0.  ]
  [ 0.    0.21 -1.02  0.  ]
  [ 0.   -0.66  1.7   0.  ]
  [ 0.    0.    0.    0.  ]]

 [[ 0.    0.    0.    0.  ]
  [ 0.   -0.76 -1.25  0.  ]
  [ 0.    0.27  0.58  0.  ]
  [ 0.    0.    0.    0.  ]]

 [[ 0.    0.    0.    0.  ]
  [ 0.    0.    0.    0.  ]
  [ 0.    0.    0.    0.  ]
  [ 0.    0.    0.    0.  ]]]



## reshapeの動作確認

In [3]:
A = np.arange(36).reshape(3, 3, 4)
print("A=",A, "\n")
B = A.reshape(3, -1)
print("B=",B, "\n")
C = A.reshape(3*3, -1)
print("C=",C)

A= [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]] 

B= [[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]] 

C= [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]


## transposeの動作確認

In [4]:
N=2; C=3; filter_h=3; filter_w=3; out_h=2; out_w=2
num = N*C*filter_h*filter_w*out_h*out_w
col = np.arange(num).reshape(N, C, filter_h, filter_w, out_h, out_w)

print("#############元データ#############")
print("col.shape=",col.shape)
print("col=", col)
print()

print("#############transpose後#############")
print(col.transpose(0,4,5,1,2,3))
print()

print("#############transposeしてからreshape#############")
print(col.transpose(0,4,5,1,2,3).reshape(N*out_h*out_w, -1))

#############元データ#############
col.shape= (2, 3, 3, 3, 2, 2)
col= [[[[[[  0   1]
     [  2   3]]

    [[  4   5]
     [  6   7]]

    [[  8   9]
     [ 10  11]]]


   [[[ 12  13]
     [ 14  15]]

    [[ 16  17]
     [ 18  19]]

    [[ 20  21]
     [ 22  23]]]


   [[[ 24  25]
     [ 26  27]]

    [[ 28  29]
     [ 30  31]]

    [[ 32  33]
     [ 34  35]]]]



  [[[[ 36  37]
     [ 38  39]]

    [[ 40  41]
     [ 42  43]]

    [[ 44  45]
     [ 46  47]]]


   [[[ 48  49]
     [ 50  51]]

    [[ 52  53]
     [ 54  55]]

    [[ 56  57]
     [ 58  59]]]


   [[[ 60  61]
     [ 62  63]]

    [[ 64  65]
     [ 66  67]]

    [[ 68  69]
     [ 70  71]]]]



  [[[[ 72  73]
     [ 74  75]]

    [[ 76  77]
     [ 78  79]]

    [[ 80  81]
     [ 82  83]]]


   [[[ 84  85]
     [ 86  87]]

    [[ 88  89]
     [ 90  91]]

    [[ 92  93]
     [ 94  95]]]


   [[[ 96  97]
     [ 98  99]]

    [[100 101]
     [102 103]]

    [[104 105]
     [106 107]]]]]




 [[[[[108 109]
     [110 111]]

    [[112 11