# Embeddingレイヤを確認する
Embeddingレイヤは、単語IDを埋め込みベクトルに変換するためのレイヤである

In [1]:
import numpy as np

In [2]:
# 確認
a = b = np.ones((5,3))
print("a=",a, "\n")
print("b=",b, "\n")
a.fill(3)  #　numpyの配列の各要素に同じ値を代入する
b = 3 # 変数に値を代入する
print("a=",a, "\n")
print("b=",b, "\n")
print()

dW = np.random.rand(2,3)
print(dW)
print()
idx = 1
dout = np.array([1,2,3])
np.add.at(dW, idx, dout) #  dWのidx行目にベクトルdoutを加える処理
print(dW)

a= [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

b= [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

a= [[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]] 

b= 3 


[[0.82732974 0.32393073 0.12397038]
 [0.79192243 0.51291291 0.74195848]]

[[0.82732974 0.32393073 0.12397038]
 [1.79192243 2.51291291 3.74195848]]


In [3]:
class Embedding:
    def __init__(self, W):
        """
        W : 重み行列, word2vecの埋め込み行列に相当する。配列形状は、(語彙数、埋め込みベクトルの要素数)
        """
        self.params = [W] # 要素は1つだけであるが、他のレイヤと仕様を揃えるため、あえてリストで定義
        self.grads = [np.zeros_like(W)] # 要素は1つだけであるが、他のレイヤと仕様を揃えるため、あえてリストで定義
        self.idx = None

    def forward(self, idx):
        """
        順伝播計算
        """
        W = self.params[0]
        self.idx = idx
        
        # 埋め込み行列から埋め込みベクトルを取り出す
        out = W[idx]
        
        return out

    def backward(self, dout):
        """
        逆伝播計算
        """
        # gradsというリストの1要素目を参照する
        dW = self.grads[0]
        
        # 配列の全ての要素に0を代入する
        dW.fill(0)
        
        # dWのidxの場所にdoutを加える
        np.add.at(dW, self.idx, dout)
        return None

In [4]:
V = 10 # 語彙数
D = 3 # 埋め込みベクトルの要素数

# パラメータの初期化
embed_W = np.random.randn(V, D) 
print("embed_W=", embed_W)
print()

# オブジェクトの生成
emb = Embedding(embed_W)

# 単語ID
idx = 2

# 順伝播計算
emb.forward(idx)

# 逆伝播計算
dout = np.arange(D)
print("dout=", dout)
print()
emb.backward(dout)
print("dW=", emb.grads[0])
print()

embed_W= [[-0.38085231 -0.50923448 -0.60461922]
 [-0.08405764  0.18403951 -0.54518601]
 [-0.05312275  1.32609237 -0.82539237]
 [-0.61889971 -1.24201737  0.24590783]
 [-1.0215016  -0.16541799 -0.81127647]
 [ 0.17635847  0.03600686  0.84432257]
 [ 1.60290218  1.09709585  0.06469014]
 [ 0.13623434  1.12033241  0.82404996]
 [-0.69778427 -0.11076736  0.14223766]
 [-0.35395715  1.07079204 -1.43577054]]

dout= [0 1 2]

dW= [[0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

